apiVersion: v1
kind: Pod
metadata:
  name: pod-hw1
  namespace: homework
  labels:
    app: hw1
spec:
  containers:
  - name: main-container
    image: busybox:stable
    command: ["sh", "-c", "httpd -fv -p 8000"]
    workingDir: /homework
    ports:
      - containerPort: 8000
    volumeMounts:
    - name: hw-volume
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  initContainers:
  - name: init-container
    image: busybox:stable
    volumeMounts:
    - name: hw-volume
      mountPath: "/init"
    command: ["/bin/sh", "-c", 'echo "[Homework #1] Hello, World!" > /init/index.html']
  volumes:
  - name: hw-volume
    emptyDir: {}